#!/bin/bash

#mvn -Pprod clean install -DskipTests

#ssh -i "~/.ssh/home.pem" ec2-user@ec2-52-37-180-39.us-west-2.compute.amazonaws.com

#ssh root@104.238.176.254 '/etc/init.d/securityalarm stop'
scp -i "~/.ssh/key2.pem" target/*.war ec2-user@ec2-52-37-180-39.us-west-2.compute.amazonaws.com:~/app/
#ssh root@104.238.176.254 '/etc/init.d/securityalarm start'
