#!/bin/bash

mvn -Pprod clean install -DskipTests

#ssh -i "~/.ssh/home.pem" ec2-user@ec2-35-164-7-108.us-west-2.compute.amazonaws.com

#ssh root@104.238.176.254 '/etc/init.d/securityalarm stop'
scp -i "~/.ssh/home.pem" target/*.war ec2-user@ec2-35-164-7-108.us-west-2.compute.amazonaws.com:~/app/
#ssh root@104.238.176.254 '/etc/init.d/securityalarm start'
